<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Rates based on typical private hospital pricing in Tanzania (2026)
     * All amounts in Tanzanian Shillings (TSh)
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        $services = [
            // CONSULTATION SERVICES
            [
                'service_code' => 'CONS-001',
                'service_name' => 'General Practitioner Consultation',
                'category' => 'consultation',
                'department' => 'Outpatient',
                'description' => 'Standard consultation with general practitioner',
                'standard_charge' => 30000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'CONS-002',
                'service_name' => 'Specialist Consultation',
                'category' => 'consultation',
                'department' => 'Outpatient',
                'description' => 'Consultation with medical specialist (Cardiologist, Neurologist, etc.)',
                'standard_charge' => 60000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'CONS-003',
                'service_name' => 'Pediatric Consultation',
                'category' => 'consultation',
                'department' => 'Pediatrics',
                'description' => 'Consultation with pediatrician',
                'standard_charge' => 40000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'CONS-004',
                'service_name' => 'Gynecology Consultation',
                'category' => 'consultation',
                'department' => 'Obstetrics & Gynecology',
                'description' => 'Consultation with gynecologist',
                'standard_charge' => 50000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'CONS-005',
                'service_name' => 'Follow-up Consultation',
                'category' => 'consultation',
                'department' => 'Outpatient',
                'description' => 'Follow-up visit with same doctor',
                'standard_charge' => 20000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // LABORATORY SERVICES
            [
                'service_code' => 'LAB-001',
                'service_name' => 'Complete Blood Count (CBC)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Full blood count analysis',
                'standard_charge' => 15000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-002',
                'service_name' => 'Blood Sugar (Random)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Random blood glucose test',
                'standard_charge' => 5000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-003',
                'service_name' => 'Blood Sugar (Fasting)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Fasting blood glucose test',
                'standard_charge' => 8000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-004',
                'service_name' => 'Malaria Test (RDT)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Rapid diagnostic test for malaria',
                'standard_charge' => 8000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-005',
                'service_name' => 'Malaria Test (Microscopy)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Microscopic examination for malaria parasites',
                'standard_charge' => 10000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-006',
                'service_name' => 'Urine Analysis',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Complete urine analysis',
                'standard_charge' => 10000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-007',
                'service_name' => 'Stool Analysis',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Comprehensive stool examination',
                'standard_charge' => 12000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-008',
                'service_name' => 'HIV Test',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'HIV antibody screening test',
                'standard_charge' => 15000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-009',
                'service_name' => 'Liver Function Test (LFT)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Complete liver function panel',
                'standard_charge' => 35000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-010',
                'service_name' => 'Kidney Function Test (RFT)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Renal function test panel',
                'standard_charge' => 30000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-011',
                'service_name' => 'Lipid Profile',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Cholesterol and triglycerides panel',
                'standard_charge' => 40000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-012',
                'service_name' => 'Typhoid Test (Widal)',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Widal test for typhoid fever',
                'standard_charge' => 15000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-013',
                'service_name' => 'Pregnancy Test',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'Urine or blood pregnancy test',
                'standard_charge' => 10000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'LAB-014',
                'service_name' => 'Blood Grouping & Rh Typing',
                'category' => 'laboratory',
                'department' => 'Laboratory',
                'description' => 'ABO blood group and Rh factor determination',
                'standard_charge' => 12000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // RADIOLOGY SERVICES
            [
                'service_code' => 'RAD-001',
                'service_name' => 'Chest X-Ray',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Chest radiograph (PA/Lateral)',
                'standard_charge' => 25000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-002',
                'service_name' => 'Abdominal X-Ray',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Abdominal radiograph',
                'standard_charge' => 30000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-003',
                'service_name' => 'Pelvic X-Ray',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Pelvic region radiograph',
                'standard_charge' => 30000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-004',
                'service_name' => 'Ultrasound - Abdomen',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Abdominal ultrasound scan',
                'standard_charge' => 60000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-005',
                'service_name' => 'Ultrasound - Obstetric',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Pregnancy ultrasound scan',
                'standard_charge' => 50000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-006',
                'service_name' => 'Ultrasound - Pelvic',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Pelvic ultrasound scan',
                'standard_charge' => 55000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-007',
                'service_name' => 'CT Scan - Head',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Computerized tomography of head',
                'standard_charge' => 250000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-008',
                'service_name' => 'CT Scan - Abdomen',
                'category' => 'radiology',
                'department' => 'Radiology',
                'description' => 'Computerized tomography of abdomen',
                'standard_charge' => 300000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'RAD-009',
                'service_name' => 'ECG (Electrocardiogram)',
                'category' => 'radiology',
                'department' => 'Cardiology',
                'description' => 'Electrocardiogram test',
                'standard_charge' => 20000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // PROCEDURE SERVICES
            [
                'service_code' => 'PROC-001',
                'service_name' => 'Wound Dressing (Small)',
                'category' => 'procedure',
                'department' => 'Outpatient',
                'description' => 'Dressing for minor wounds',
                'standard_charge' => 15000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-002',
                'service_name' => 'Wound Dressing (Large)',
                'category' => 'procedure',
                'department' => 'Outpatient',
                'description' => 'Dressing for major wounds',
                'standard_charge' => 30000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-003',
                'service_name' => 'Suturing (Minor)',
                'category' => 'procedure',
                'department' => 'Emergency',
                'description' => 'Simple wound closure with sutures',
                'standard_charge' => 40000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-004',
                'service_name' => 'Suturing (Major)',
                'category' => 'procedure',
                'department' => 'Emergency',
                'description' => 'Complex wound closure with sutures',
                'standard_charge' => 80000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-005',
                'service_name' => 'Injection - Intramuscular',
                'category' => 'procedure',
                'department' => 'Nursing',
                'description' => 'IM injection administration',
                'standard_charge' => 5000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-006',
                'service_name' => 'Injection - Intravenous',
                'category' => 'procedure',
                'department' => 'Nursing',
                'description' => 'IV injection administration',
                'standard_charge' => 8000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-007',
                'service_name' => 'IV Cannulation',
                'category' => 'procedure',
                'department' => 'Nursing',
                'description' => 'Intravenous cannula insertion',
                'standard_charge' => 10000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-008',
                'service_name' => 'Catheterization',
                'category' => 'procedure',
                'department' => 'Nursing',
                'description' => 'Urinary catheter insertion',
                'standard_charge' => 25000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-009',
                'service_name' => 'Nebulization',
                'category' => 'procedure',
                'department' => 'Emergency',
                'description' => 'Respiratory nebulizer treatment',
                'standard_charge' => 15000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PROC-010',
                'service_name' => 'Ear Syringing',
                'category' => 'procedure',
                'department' => 'ENT',
                'description' => 'Ear wax removal by irrigation',
                'standard_charge' => 20000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // EMERGENCY SERVICES
            [
                'service_code' => 'EMER-001',
                'service_name' => 'Emergency Room Visit',
                'category' => 'emergency',
                'department' => 'Emergency',
                'description' => 'Emergency department consultation and initial assessment',
                'standard_charge' => 50000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'EMER-002',
                'service_name' => 'Ambulance Service (Within City)',
                'category' => 'emergency',
                'department' => 'Emergency',
                'description' => 'Emergency ambulance transport within city limits',
                'standard_charge' => 100000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'EMER-003',
                'service_name' => 'Oxygen Therapy (Per Hour)',
                'category' => 'emergency',
                'department' => 'Emergency',
                'description' => 'Oxygen administration per hour',
                'standard_charge' => 10000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // SURGERY SERVICES
            [
                'service_code' => 'SURG-001',
                'service_name' => 'Minor Surgery',
                'category' => 'surgery',
                'department' => 'Surgery',
                'description' => 'Minor surgical procedures under local anesthesia',
                'standard_charge' => 200000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'SURG-002',
                'service_name' => 'Appendectomy',
                'category' => 'surgery',
                'department' => 'Surgery',
                'description' => 'Surgical removal of appendix',
                'standard_charge' => 1500000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'SURG-003',
                'service_name' => 'Cesarean Section',
                'category' => 'surgery',
                'department' => 'Obstetrics & Gynecology',
                'description' => 'C-section delivery',
                'standard_charge' => 2000000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'SURG-004',
                'service_name' => 'Normal Delivery',
                'category' => 'surgery',
                'department' => 'Obstetrics & Gynecology',
                'description' => 'Vaginal delivery with assistance',
                'standard_charge' => 800000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'SURG-005',
                'service_name' => 'Hernia Repair',
                'category' => 'surgery',
                'department' => 'Surgery',
                'description' => 'Inguinal/umbilical hernia repair',
                'standard_charge' => 1800000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ROOM CHARGES
            [
                'service_code' => 'ROOM-001',
                'service_name' => 'General Ward (Per Day)',
                'category' => 'room_charge',
                'department' => 'IPD',
                'description' => 'General ward bed per day',
                'standard_charge' => 50000.00,
                'taxable' => false,
                'tax_percentage' => 0.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'ROOM-002',
                'service_name' => 'Private Room (Per Day)',
                'category' => 'room_charge',
                'department' => 'IPD',
                'description' => 'Private room per day',
                'standard_charge' => 120000.00,
                'taxable' => false,
                'tax_percentage' => 0.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'ROOM-003',
                'service_name' => 'ICU (Per Day)',
                'category' => 'room_charge',
                'department' => 'ICU',
                'description' => 'Intensive Care Unit per day',
                'standard_charge' => 300000.00,
                'taxable' => false,
                'tax_percentage' => 0.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'ROOM-004',
                'service_name' => 'Maternity Ward (Per Day)',
                'category' => 'room_charge',
                'department' => 'Maternity',
                'description' => 'Maternity ward bed per day',
                'standard_charge' => 80000.00,
                'taxable' => false,
                'tax_percentage' => 0.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // NURSING CARE
            [
                'service_code' => 'NURS-001',
                'service_name' => 'Nursing Care (Per Day)',
                'category' => 'nursing_care',
                'department' => 'Nursing',
                'description' => 'Daily nursing care and monitoring',
                'standard_charge' => 20000.00,
                'taxable' => false,
                'tax_percentage' => 0.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'NURS-002',
                'service_name' => 'IV Fluid Administration',
                'category' => 'nursing_care',
                'department' => 'Nursing',
                'description' => 'Intravenous fluid therapy setup and monitoring',
                'standard_charge' => 15000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'NURS-003',
                'service_name' => 'Vital Signs Monitoring',
                'category' => 'nursing_care',
                'department' => 'Nursing',
                'description' => 'Regular vital signs monitoring and charting',
                'standard_charge' => 5000.00,
                'taxable' => false,
                'tax_percentage' => 0.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // OTHER SERVICES
            [
                'service_code' => 'OTH-001',
                'service_name' => 'Medical Certificate',
                'category' => 'other',
                'department' => 'Administration',
                'description' => 'Medical fitness certificate',
                'standard_charge' => 20000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'OTH-002',
                'service_name' => 'Medical Report',
                'category' => 'other',
                'department' => 'Administration',
                'description' => 'Detailed medical report for insurance/legal purposes',
                'standard_charge' => 50000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'OTH-003',
                'service_name' => 'Vaccination - Adult',
                'category' => 'other',
                'department' => 'Outpatient',
                'description' => 'Adult vaccination service (vaccine cost separate)',
                'standard_charge' => 10000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'OTH-004',
                'service_name' => 'Vaccination - Child',
                'category' => 'other',
                'department' => 'Pediatrics',
                'description' => 'Child vaccination service (vaccine cost separate)',
                'standard_charge' => 10000.00,
                'taxable' => false,
                'tax_percentage' => 0.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // PHARMACY SERVICES (Hybrid Approach)
            [
                'service_code' => 'PHARM-001',
                'service_name' => 'Pharmacy Dispensing Fee',
                'category' => 'pharmacy',
                'department' => 'Pharmacy',
                'description' => 'Professional dispensing service fee (added per prescription)',
                'standard_charge' => 5000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_code' => 'PHARM-002',
                'service_name' => 'Medication Counseling',
                'category' => 'pharmacy',
                'department' => 'Pharmacy',
                'description' => 'Pharmacist consultation and medication counseling',
                'standard_charge' => 10000.00,
                'taxable' => true,
                'tax_percentage' => 18.00,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('services')->insert($services);
        
        $this->command->info('Service catalog seeded successfully with ' . count($services) . ' services.');
    }
}
